paths:
  "/api/v4/users/{id}/events":
    get:
      summary: Get the contribution events of a specified user
      description: This feature was introduced in GitLab 8.13.
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: The ID or username of the user
        type: string
        required: true
      - in: query
        name: page
        description: Current page number
        type: integer
        format: int32
        default: 1
        required: false
        example: 1
      - in: query
        name: per_page
        description: Number of items per page
        type: integer
        format: int32
        default: 20
        required: false
        example: 20
      - in: query
        name: action
        description: Event action to filter on
        type: string
        required: false
      - in: query
        name: target_type
        description: Event target type to filter on
        type: string
        enum:
        - issue
        - milestone
        - merge_request
        - note
        - project
        - snippet
        - user
        - wiki
        - design
        required: false
      - in: query
        name: before
        description: Include only events created before this date
        type: string
        format: date
        required: false
      - in: query
        name: after
        description: Include only events created after this date
        type: string
        format: date
        required: false
      - in: query
        name: sort
        description: Return events sorted in ascending and descending order
        type: string
        default: desc
        enum:
        - asc
        - desc
        required: false
      responses:
        '200':
          description: Get the contribution events of a specified user
          schema:
            type: array
            items:
              "$ref": "#/definitions/API_Entities_Event"
        '404':
          description: Not found
      tags:
      - events
      operationId: getApiV4UsersIdEvents


